os: osx
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=3.6
  - source activate test-environment
  - conda install -c anaconda cython
  - /usr/libexec/java_home
  - /usr/libexec/java_home --arch x86_64
  - ls /Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home
  - ls /Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home/jre-10/lib
  - ls /Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home/jre-10/lib/server
  - pip install --progress-bar off -e .
script:
  - microscoper
